'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertCircle, BarChart3, Bell, BookOpen, Boxes, BriefcaseBusiness, CheckCircle2,
  ChevronDown, CircleDot, ClipboardList, Clock3, FileText, Filter, FolderKanban, Gauge,
  Globe2, LayoutDashboard, Menu, MoreHorizontal, Package, Plus, Search, Settings, ShoppingCart,
  Sparkles, Tag, Truck, Users, X, Zap
} from 'lucide-react';

type Status = 'To Do'|'In Progress'|'Waiting'|'Blocked'|'Done'|'Cancelled';
type Priority = 'Urgent'|'High'|'Medium'|'Low';
type ProjectStatus = 'Planning'|'Active'|'On Hold'|'Completed'|'Cancelled';

type Task={id:string; title:string; description:string; projectId:string; status:Status; priority:Priority; due:string; tags:string[]; subtasks:{id:string;title:string;done:boolean}[]; created:string; updated:string};
type Project={id:string;name:string;description:string;status:ProjectStatus;priority:Priority;category:string;due:string;goals:string};
type Note={id:string;title:string;body:string;tag:string;pinned:boolean;updated:string};
type Order={id:string;marketplace:string;date:string;product:string;qty:number;amount:number;invoice:string;shipment:string;overall:string;priority:Priority;owner:string;notes:string};
type Issue={id:string;title:string;order:string;category:string;owner:string;priority:Priority;status:string;due:string;resolution:string;notes:string};
type Campaign={id:string;name:string;type:string;audience:string;start:string;end:string;status:string;targeted:number;sent:number;delivered:number;clicks:number;orders:number;revenue:number;notes:string;results:string;learnings:string};
type Experiment={id:string;name:string;hypothesis:string;problem:string;action:string;channel:string;start:string;end:string;metric:string;baseline:string;target:string;result:string;learning:string;decision:string};
type Ecommerce={id:string;marketplace:string;date:string;orders:number;revenue:number;units:number;cancellations:number;returns:number;stockouts:number;notes:string};

const uid=()=>Math.random().toString(36).slice(2,10);
const today=()=>new Date().toISOString().slice(0,10);
const seed={
 projects:[
  {id:'p1',name:'Blinkit Growth',description:'Improve marketplace sales, availability and execution.',status:'Active',priority:'High',category:'E-Commerce',due:'2026-10-05',goals:'Increase orders and reduce operational friction.'},
  {id:'p2',name:'Website Conversion Improvement',description:'Conversion, content and product-page improvements.',status:'Active',priority:'Medium',category:'Growth',due:'2026-10-15',goals:'Improve website conversion and AOV.'},
  {id:'p3',name:'WhatsApp CRM',description:'Retention and reorder campaign planning.',status:'Planning',priority:'Medium',category:'CRM',due:'2026-10-20',goals:'Build repeat purchase workflows.'},
  {id:'p4',name:'Operations Cleanup',description:'Resolve open fulfillment and invoice issues.',status:'Active',priority:'Urgent',category:'Operations',due:'2026-09-28',goals:'Reduce waiting orders and close shipment issues.'}
 ] as Project[],
 tasks:[
  {id:'t1',title:'Check Blinkit RO #1023',description:'Verify inventory, invoice and shipment status.',projectId:'p1',status:'Waiting',priority:'Urgent',due:'2026-09-20',tags:['Blinkit','RO'],subtasks:[{id:'s1',title:'Verify RO',done:true},{id:'s2',title:'Check inventory',done:true},{id:'s3',title:'Create invoice',done:false},{id:'s4',title:'Confirm shipment',done:false}],created:'2026-09-19',updated:'2026-09-20'},
  {id:'t2',title:'Follow up with Operations regarding dispatch',description:'Confirm dispatch timing and owner.',projectId:'p4',status:'In Progress',priority:'High',due:'2026-09-20',tags:['Operations'],subtasks:[],created:'2026-09-19',updated:'2026-09-20'},
  {id:'t3',title:'Create WhatsApp reorder campaign',description:'Draft audience, message and measurement plan.',projectId:'p3',status:'To Do',priority:'Medium',due:'2026-09-22',tags:['CRM','WhatsApp'],subtasks:[],created:'2026-09-18',updated:'2026-09-19'},
  {id:'t4',title:'Review cancellation rate',description:'Review last 7 days marketplace cancellation patterns.',projectId:'p1',status:'Done',priority:'Medium',due:'2026-09-19',tags:['Analytics'],subtasks:[],created:'2026-09-17',updated:'2026-09-19'},
  {id:'t5',title:'Update website product',description:'Refresh product details and promotional copy.',projectId:'p2',status:'To Do',priority:'Low',due:'2026-09-23',tags:['Website'],subtasks:[],created:'2026-09-18',updated:'2026-09-18'}
 ] as Task[],
 notes:[{id:'n1',title:'Founder instructions',body:'Capture weekly priorities and important follow-ups here.',tag:'Founder',pinned:true,updated:'2026-09-20'}] as Note[],
 orders:[{id:'RO-1023',marketplace:'Blinkit',date:'2026-09-20',product:'Impact Water 1L',qty:48,amount:5760,invoice:'Pending',shipment:'Waiting',overall:'Waiting',priority:'Urgent',owner:'Operations',notes:'Awaiting dispatch confirmation.'},{id:'RO-1019',marketplace:'Zepto',date:'2026-09-19',product:'Impact Water 500ml',qty:96,amount:7680,invoice:'Sent',shipment:'Dispatched',overall:'Dispatched',priority:'High',owner:'Delivery Team',notes:''}] as Order[],
 issues:[{id:'i1',title:'RO-1023 dispatch pending',order:'RO-1023',category:'Shipment',owner:'Operations',priority:'Urgent',status:'Open',due:'2026-09-20',resolution:'',notes:'Follow up before EOD.'}] as Issue[],
 campaigns:[{id:'c1',name:'September Reorder Push',type:'Reorder',audience:'Recent customers',start:'2026-09-22',end:'2026-09-28',status:'Planned',targeted:1200,sent:0,delivered:0,clicks:0,orders:0,revenue:0,notes:'',results:'',learnings:''}] as Campaign[],
 experiments:[{id:'e1',name:'2-pack bundle test',hypothesis:'Customers may buy more if offered a 2-pack bundle.',problem:'Increase AOV.',action:'Test 2-pack bundle on website.',channel:'Website',start:'2026-09-23',end:'2026-10-07',metric:'AOV',baseline:'',target:'',result:'',learning:'',decision:'Continue'}] as Experiment[],
 ecommerce:[{id:'ec1',marketplace:'Blinkit',date:'2026-09-19',orders:84,revenue:98200,units:120,cancellations:4,returns:2,stockouts:1,notes:''},{id:'ec2',marketplace:'Zepto',date:'2026-09-19',orders:61,revenue:72100,units:88,cancellations:3,returns:1,stockouts:2,notes:''},{id:'ec3',marketplace:'Website',date:'2026-09-19',orders:32,revenue:45600,units:52,cancellations:1,returns:0,stockouts:0,notes:''}] as Ecommerce[]
};

const nav=[['Dashboard',LayoutDashboard],['Tasks',ClipboardList],['Projects',FolderKanban],['E-Commerce',ShoppingCart],['Operations',Truck],['CRM',Users],['Growth',Sparkles],['Website',Globe2],['Reports',BarChart3],['Notes',BookOpen],['Settings',Settings]] as const;
const statuses:Status[]=['To Do','In Progress','Waiting','Blocked','Done','Cancelled'];
const priorities:Priority[]=['Urgent','High','Medium','Low'];
const projectStatuses:ProjectStatus[]=['Planning','Active','On Hold','Completed','Cancelled'];

function load<T>(key:string, fallback:T):T { if(typeof window==='undefined') return fallback; try{return JSON.parse(localStorage.getItem('impact:'+key)||'null')||fallback}catch{return fallback} }
function save(key:string,val:unknown){localStorage.setItem('impact:'+key,JSON.stringify(val));}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:string}){return <span className={'badge badge-'+tone}>{children}</span>}
function priorityTone(p:Priority){return p==='Urgent'?'red':p==='High'?'orange':p==='Medium'?'yellow':'gray'}
function statusTone(s:string){return s==='Done'||s==='Completed'||s==='Dispatched'?'green':s==='Waiting'||s==='On Hold'?'yellow':s==='Blocked'||s==='Failed'?'red':'blue'}

export default function Home(){
 const [authed,setAuthed]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
 const [page,setPage]=useState('Dashboard'); const [query,setQuery]=useState(''); const [showAdd,setShowAdd]=useState(false); const [mobileOpen,setMobileOpen]=useState(false);
 const [projects,setProjects]=useState<Project[]>(seed.projects),[tasks,setTasks]=useState<Task[]>(seed.tasks),[notes,setNotes]=useState<Note[]>(seed.notes),[orders,setOrders]=useState<Order[]>(seed.orders),[issues,setIssues]=useState<Issue[]>(seed.issues),[campaigns,setCampaigns]=useState<Campaign[]>(seed.campaigns),[experiments,setExperiments]=useState<Experiment[]>(seed.experiments),[ecommerce,setEcommerce]=useState<Ecommerce[]>(seed.ecommerce);
 useEffect(()=>{if(localStorage.getItem('impact:auth')==='1')setAuthed(true); setProjects(load('projects',seed.projects));setTasks(load('tasks',seed.tasks));setNotes(load('notes',seed.notes));setOrders(load('orders',seed.orders));setIssues(load('issues',seed.issues));setCampaigns(load('campaigns',seed.campaigns));setExperiments(load('experiments',seed.experiments));setEcommerce(load('ecommerce',seed.ecommerce));},[]);
 useEffect(()=>{save('projects',projects)},[projects]);useEffect(()=>{save('tasks',tasks)},[tasks]);useEffect(()=>{save('notes',notes)},[notes]);useEffect(()=>{save('orders',orders)},[orders]);useEffect(()=>{save('issues',issues)},[issues]);useEffect(()=>{save('campaigns',campaigns)},[campaigns]);useEffect(()=>{save('experiments',experiments)},[experiments]);useEffect(()=>{save('ecommerce',ecommerce)},[ecommerce]);
 const dueToday=tasks.filter(t=>t.due===today()&&t.status!=='Done'&&t.status!=='Cancelled'); const overdue=tasks.filter(t=>t.due<today()&&t.status!=='Done'&&t.status!=='Cancelled'); const waiting=tasks.filter(t=>t.status==='Waiting'); const activeProjects=projects.filter(p=>p.status==='Active');
 const projectProgress=(id:string)=>{const ts=tasks.filter(t=>t.projectId===id); if(!ts.length)return 0; return Math.round(ts.filter(t=>t.status==='Done').length/ts.length*100)};
 const logout=()=>{localStorage.removeItem('impact:auth');setAuthed(false)};
 if(!authed)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} onLogin={()=>{localStorage.setItem('impact:auth','1');setAuthed(true)}}/>;
 return <div className="app-shell">
  <aside className={'sidebar '+(mobileOpen?'open':'')}><div className="brand"><div className="brand-mark">IW</div><div className="brand-text"><b>Impact Water</b><small>Growth OS</small></div></div><div className="workspace">OPERATIONS WORKSPACE</div>{nav.map(([n,I])=><button key={n} className={'nav-item '+(page===n?'active':'')} onClick={()=>{setPage(n);setMobileOpen(false)}}><I size={18}/><span className="nav-label">{n}</span></button>)}<div className="sidebar-bottom"><div className="user-chip"><div className="avatar">J</div><div className="nav-label"><b>Jagadeesh</b><small>Founder&apos;s Office</small></div></div><button className="nav-item" onClick={logout}><X size={18}/><span className="nav-label">Log out</span></button></div></aside>
  {mobileOpen&&<div className="scrim" onClick={()=>setMobileOpen(false)}/>}<main className="main"><header className="topbar"><div className="top-left"><button className="mobile-menu btn" onClick={()=>setMobileOpen(true)}><Menu size={18}/></button><div className="crumb">{page}</div></div><div className="top-actions"><button className="search-trigger" onClick={()=>document.getElementById('global-search')?.focus()}><Search size={16}/> Search <kbd>⌘ K</kbd></button><button className="icon-btn"><Bell size={18}/><span className="dot"/></button><button className="quick-add" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add</button></div></header>
  <div className="content">{page==='Dashboard'&&<Dashboard tasks={tasks} projects={projects} dueToday={dueToday} overdue={overdue} waiting={waiting} activeProjects={activeProjects} projectProgress={projectProgress} setTasks={setTasks} setPage={setPage}/>} {page==='Tasks'&&<TasksPage tasks={tasks} projects={projects} setTasks={setTasks} query={query}/>} {page==='Projects'&&<ProjectsPage projects={projects} tasks={tasks} setProjects={setProjects} projectProgress={projectProgress}/>} {page==='E-Commerce'&&<EcommercePage ecommerce={ecommerce} setEcommerce={setEcommerce} orders={orders} setOrders={setOrders}/>} {page==='Operations'&&<OperationsPage orders={orders} issues={issues} setIssues={setIssues}/>} {page==='CRM'&&<CampaignPage campaigns={campaigns} setCampaigns={setCampaigns}/>} {page==='Growth'&&<GrowthPage experiments={experiments} setExperiments={setExperiments}/>} {page==='Website'&&<WebsitePage tasks={tasks} setTasks={setTasks} projects={projects}/>} {page==='Reports'&&<Reports tasks={tasks} projects={projects} orders={orders} issues={issues} campaigns={campaigns} experiments={experiments}/>} {page==='Notes'&&<NotesPage notes={notes} setNotes={setNotes} query={query}/>} {page==='Settings'&&<SettingsPage/>}</div></main>
  <div className="global-search"><input id="global-search" placeholder="Search tasks, projects, orders, notes…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
  {showAdd&&<QuickAdd onClose={()=>setShowAdd(false)} setPage={setPage} setTasks={setTasks} setProjects={setProjects} setOrders={setOrders} setNotes={setNotes} setIssues={setIssues} setCampaigns={setCampaigns} setExperiments={setExperiments}/>} 
 </div>
}

function Login({email,password,setEmail,setPassword,onLogin}:{email:string;password:string;setEmail:(x:string)=>void;setPassword:(x:string)=>void;onLogin:()=>void}){return <div className="login"><div className="login-card"><div className="brand center"><div className="brand-mark">IW</div><div><b>Impact Water</b><small>E-commerce & Growth OS</small></div></div><div className="eyebrow">INTERNAL WORKSPACE</div><h1>Run your day from one place.</h1><p>Orders, operations, growth, CRM and projects — designed around the work you actually do.</p><label>Email<input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@impactwater.in"/></label><label>Password<input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="btn btn-primary wide" onClick={onLogin}>Sign in</button><div className="demo-note"><CircleDot size={14}/> Demo mode — data is stored locally until Supabase is configured.</div></div></div>}

function PageTitle({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc?:string;action?:React.ReactNode}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{action}</div>}
function Stat({label,value,icon:Icon,tone='blue',sub}:{label:string;value:string|number;icon:any;tone?:string;sub?:string}){return <div className="stat card"><div className={'stat-icon '+tone}><Icon size={18}/></div><div><div className="stat-value">{value}</div><div className="stat-label">{label}</div>{sub&&<div className="stat-sub">{sub}</div>}</div></div>}
function Dashboard({tasks,projects,dueToday,overdue,waiting,activeProjects,projectProgress,setTasks,setPage}:{tasks:Task[];projects:Project[];dueToday:Task[];overdue:Task[];waiting:Task[];activeProjects:Project[];projectProgress:(id:string)=>number;setTasks:React.Dispatch<React.SetStateAction<Task[]>>;setPage:(x:string)=>void}){const priority=tasks.filter(t=>t.status!=='Done'&&t.status!=='Cancelled').sort((a,b)=>priorities.indexOf(a.priority)-priorities.indexOf(b.priority)).slice(0,4);return <><PageTitle eyebrow="Sunday · 20 September 2026" title="Good evening, Jagadeesh." desc="Here’s what needs your attention today." action={<button className="btn btn-primary" onClick={()=>setPage('Tasks')}><ClipboardList size={16}/> Open task board</button>}/><div className="stats grid-6"><Stat label="Open tasks" value={tasks.filter(t=>!['Done','Cancelled'].includes(t.status)).length} icon={ClipboardList}/><Stat label="Due today" value={dueToday.length} icon={Clock3} tone="orange"/><Stat label="Overdue" value={overdue.length} icon={AlertCircle} tone="red"/><Stat label="Waiting" value={waiting.length} icon={Truck} tone="yellow"/><Stat label="Completed today" value={tasks.filter(t=>t.status==='Done'&&t.updated===today()).length} icon={CheckCircle2} tone="green"/><Stat label="Active projects" value={activeProjects.length} icon={FolderKanban}/></div><div className="dashboard-grid"><section className="card section"><SectionHead title="Needs attention" icon={Zap}/>{priority.map(t=><TaskRow key={t.id} task={t} onDone={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,status:'Done',updated:today()}:x))}/>)}</section><section className="card section"><SectionHead title="My tasks today" icon={ClipboardList}/>{dueToday.length?dueToday.map(t=><TaskRow key={t.id} task={t} onDone={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,status:'Done',updated:today()}:x))}/>):<Empty text="Nothing due today."/>}</section></div><div className="dashboard-grid"><section className="card section"><SectionHead title="Active projects" icon={FolderKanban} action={<button className="link" onClick={()=>setPage('Projects')}>View all</button>}/>{activeProjects.map(p=><div className="project-row" key={p.id}><div className="project-main"><div className="project-icon"><BriefcaseBusiness size={16}/></div><div><b>{p.name}</b><small>{p.category} · Due {p.due}</small></div></div><div className="progress-wrap"><div className="progress-line"><span style={{width:projectProgress(p.id)+'%'}}/></div><small>{projectProgress(p.id)}%</small></div></div>)}</section><section className="card section"><SectionHead title="Waiting on others" icon={Truck}/>{waiting.length?waiting.map(t=><div className="waiting-row" key={t.id}><div><b>{t.title}</b><small>{t.description||'Waiting for another team or partner.'}</small></div><Badge tone="yellow">Waiting</Badge></div>):<Empty text="No waiting tasks."/>}</section></div></>}
function SectionHead({title,icon:Icon,action}:{title:string;icon:any;action?:React.ReactNode}){return <div className="section-head"><div><Icon size={17}/><h2>{title}</h2></div>{action}</div>}
function TaskRow({task,onDone}:{task:Task;onDone:()=>void}){return <div className="task-row"><button className="check" onClick={onDone}>{task.status==='Done'?<CheckCircle2 size={19}/>:<CircleDot size={19}/>}</button><div className="task-copy"><b>{task.title}</b><div><Badge tone={priorityTone(task.priority)}>{task.priority}</Badge> <Badge tone={statusTone(task.status)}>{task.status}</Badge>{task.tags.slice(0,2).map(x=><span className="tag" key={x}>{x}</span>)}</div></div><div className="task-date">{task.due}</div></div>}
function Empty({text}:{text:string}){return <div className="empty"><Boxes size={24}/><span>{text}</span></div>}

function TasksPage({tasks,projects,setTasks,query}:{tasks:Task[];projects:Project[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;query:string}){const [status,setStatus]=useState('All'),[priority,setPriority]=useState('All'),[modal,setModal]=useState(false);const [editing,setEditing]=useState<Task|null>(null);const filtered=tasks.filter(t=>(!query||`${t.title} ${t.description} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(status==='All'||t.status===status)&&(priority==='All'||t.priority===priority));const saveTask=(t:Task)=>{setTasks(xs=>xs.some(x=>x.id===t.id)?xs.map(x=>x.id===t.id?t:x):[t,...xs]);setModal(false);setEditing(null)};return <><PageTitle eyebrow="Work management" title="Tasks" desc="Keep execution moving, with waiting and blocked work visible." action={<button className="btn btn-primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> New task</button>}/><div className="toolbar"><div className="searchbox"><Search size={16}/><input placeholder="Search tasks…" value={query}/></div><select className="select compact" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select className="select compact" value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option>{priorities.map(x=><option key={x}>{x}</option>)}</select><span className="result-count">{filtered.length} tasks</span></div><div className="card task-table">{filtered.map(t=><div className="table-task" key={t.id}><button className="check" onClick={()=>setTasks(xs=>xs.map(x=>x.id===t.id?{...x,status:x.status==='Done'?'To Do':'Done',updated:today()}:x))}>{t.status==='Done'?<CheckCircle2 size={20}/>:<CircleDot size={20}/>}</button><div className="task-copy"><b>{t.title}</b><small>{projects.find(p=>p.id===t.projectId)?.name||'No project'} · {t.due}</small><div>{t.tags.map(x=><span className="tag" key={x}>{x}</span>)}{t.subtasks.length>0&&<span className="tag">{t.subtasks.filter(s=>s.done).length}/{t.subtasks.length} subtasks</span>}</div></div><Badge tone={priorityTone(t.priority)}>{t.priority}</Badge><Badge tone={statusTone(t.status)}>{t.status}</Badge><button className="icon-btn small" onClick={()=>{setEditing(t);setModal(true)}}><MoreHorizontal size={17}/></button></div>)}{!filtered.length&&<Empty text="No tasks match these filters."/>}</div>{modal&&<TaskModal task={editing} projects={projects} onClose={()=>setModal(false)} onSave={saveTask} onDelete={(id)=>{setTasks(xs=>xs.filter(x=>x.id!==id));setModal(false)}}/>}</>}
function TaskModal({task,projects,onClose,onSave,onDelete}:{task:Task|null;projects:Project[];onClose:()=>void;onSave:(t:Task)=>void;onDelete:(id:string)=>void}){const [t,setT]=useState<Task>(task||{id:uid(),title:'',description:'',projectId:projects[0]?.id||'',status:'To Do',priority:'Medium',due:today(),tags:[],subtasks:[],created:today(),updated:today()});const [sub,setSub]=useState('');return <Modal title={task?'Edit task':'New task'} onClose={onClose}><label>Task name<input className="input" value={t.title} onChange={e=>setT({...t,title:e.target.value})}/></label><label>Description<textarea className="textarea" rows={3} value={t.description} onChange={e=>setT({...t,description:e.target.value})}/></label><div className="form-grid"><label>Project<select className="select" value={t.projectId} onChange={e=>setT({...t,projectId:e.target.value})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Status<select className="select" value={t.status} onChange={e=>setT({...t,status:e.target.value as Status})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select className="select" value={t.priority} onChange={e=>setT({...t,priority:e.target.value as Priority})}>{priorities.map(s=><option key={s}>{s}</option>)}</select></label><label>Due date<input className="input" type="date" value={t.due} onChange={e=>setT({...t,due:e.target.value})}/></label></div><label>Tags<input className="input" value={t.tags.join(', ')} onChange={e=>setT({...t,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><div className="subtask-editor"><b>Subtasks</b>{t.subtasks.map(s=><div className="subline" key={s.id}><input type="checkbox" checked={s.done} onChange={e=>setT({...t,subtasks:t.subtasks.map(x=>x.id===s.id?{...x,done:e.target.checked}:x)})}/><span>{s.title}</span><button className="link danger" onClick={()=>setT({...t,subtasks:t.subtasks.filter(x=>x.id!==s.id)})}>Remove</button></div>)}<div className="inline-add"><input className="input" placeholder="Add subtask" value={sub} onChange={e=>setSub(e.target.value)}/><button className="btn" onClick={()=>{if(sub.trim()){setT({...t,subtasks:[...t.subtasks,{id:uid(),title:sub.trim(),done:false}]});setSub('')}}}><Plus size={15}/></button></div></div><div className="modal-actions">{task&&<button className="btn danger-btn" onClick={()=>onDelete(t.id)}>Delete</button>}<span/><button className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={!t.title.trim()} onClick={()=>onSave({...t,updated:today()})}>Save task</button></div></Modal>}

function ProjectsPage({projects,tasks,setProjects,projectProgress}:{projects:Project[];tasks:Task[];setProjects:React.Dispatch<React.SetStateAction<Project[]>>;projectProgress:(id:string)=>number}){const [modal,setModal]=useState(false),[editing,setEditing]=useState<Project|null>(null);const save=(p:Project)=>{setProjects(xs=>xs.some(x=>x.id===p.id)?xs.map(x=>x.id===p.id?p:x):[p,...xs]);setModal(false)};return <><PageTitle eyebrow="Portfolio" title="Projects" desc="Organize initiatives across e-commerce, operations, CRM and growth." action={<button className="btn btn-primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> New project</button>}/><div className="project-grid">{projects.map(p=><div className="card project-card" key={p.id}><div className="project-card-top"><div className="project-icon large"><FolderKanban size={20}/></div><button className="icon-btn small" onClick={()=>{setEditing(p);setModal(true)}}><MoreHorizontal size={17}/></button></div><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="project-meta"><Badge tone={statusTone(p.status)}>{p.status}</Badge><Badge tone={priorityTone(p.priority)}>{p.priority}</Badge></div><div className="progress-line"><span style={{width:projectProgress(p.id)+'%'}}/></div><div className="project-footer"><b>{projectProgress(p.id)}% complete</b><span>{tasks.filter(t=>t.projectId===p.id&&!['Done','Cancelled'].includes(t.status)).length} open tasks</span></div><small>Due {p.due}</small></div>)}</div>{modal&&<ProjectModal project={editing} onClose={()=>setModal(false)} onSave={save} onDelete={id=>{setProjects(xs=>xs.filter(x=>x.id!==id));setModal(false)}}/>}</>}
function ProjectModal({project,onClose,onSave,onDelete}:{project:Project|null;onClose:()=>void;onSave:(p:Project)=>void;onDelete:(id:string)=>void}){const [p,setP]=useState<Project>(project||{id:uid(),name:'',description:'',status:'Planning',priority:'Medium',category:'E-Commerce',due:today(),goals:''});return <Modal title={project?'Edit project':'New project'} onClose={onClose}><label>Project name<input className="input" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><label>Description<textarea className="textarea" rows={3} value={p.description} onChange={e=>setP({...p,description:e.target.value})}/></label><div className="form-grid"><label>Category<select className="select" value={p.category} onChange={e=>setP({...p,category:e.target.value})}>{['E-Commerce','Operations','CRM','Growth','Custom'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select className="select" value={p.status} onChange={e=>setP({...p,status:e.target.value as ProjectStatus})}>{projectStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select className="select" value={p.priority} onChange={e=>setP({...p,priority:e.target.value as Priority})}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label>Due date<input className="input" type="date" value={p.due} onChange={e=>setP({...p,due:e.target.value})}/></label></div><label>Goals<textarea className="textarea" rows={3} value={p.goals} onChange={e=>setP({...p,goals:e.target.value})}/></label><div className="modal-actions">{project&&<button className="btn danger-btn" onClick={()=>onDelete(p.id)}>Delete</button>}<span/><button className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={!p.name.trim()} onClick={()=>onSave(p)}>Save project</button></div></Modal>}

function EcommercePage({ecommerce,setEcommerce,orders,setOrders}:{ecommerce:Ecommerce[];setEcommerce:React.Dispatch<React.SetStateAction<Ecommerce[]>>;orders:Order[];setOrders:React.Dispatch<React.SetStateAction<Order[]>>}){const revenue=ecommerce.reduce((a,x)=>a+x.revenue,0),ord=ecommerce.reduce((a,x)=>a+x.orders,0),aov=ord?Math.round(revenue/ord):0;return <><PageTitle eyebrow="Commerce control center" title="E-Commerce" desc="Manual marketplace tracking now; integration-ready for later." action={<button className="btn btn-primary" onClick={()=>setEcommerce(xs=>[{id:uid(),marketplace:'Other',date:today(),orders:0,revenue:0,units:0,cancellations:0,returns:0,stockouts:0,notes:''},...xs])}><Plus size={16}/> Add record</button>}/><div className="stats grid-4"><Stat label="Orders" value={ord} icon={ShoppingCart}/><Stat label="Revenue" value={'₹'+revenue.toLocaleString('en-IN')} icon={BarChart3} tone="green"/><Stat label="AOV" value={'₹'+aov.toLocaleString('en-IN')} icon={Gauge} tone="purple"/><Stat label="Stock-outs" value={ecommerce.reduce((a,x)=>a+x.stockouts,0)} icon={Package} tone="orange"/></div><div className="card section"><SectionHead title="Marketplace performance" icon={ShoppingCart}/><div className="table-wrap"><table><thead><tr><th>Marketplace</th><th>Date</th><th>Orders</th><th>Revenue</th><th>Units</th><th>AOV</th><th>Cancels</th><th>Returns</th><th>Stock-outs</th></tr></thead><tbody>{ecommerce.map(x=><tr key={x.id}><td><b>{x.marketplace}</b></td><td>{x.date}</td><td>{x.orders}</td><td>₹{x.revenue.toLocaleString('en-IN')}</td><td>{x.units}</td><td>₹{x.orders?Math.round(x.revenue/x.orders).toLocaleString('en-IN'):0}</td><td>{x.cancellations}</td><td>{x.returns}</td><td>{x.stockouts}</td></tr>)}</tbody></table></div></div><div className="card section"><SectionHead title="RO / Order tracker" icon={Truck}/><div className="table-wrap"><table><thead><tr><th>RO</th><th>Marketplace</th><th>Product</th><th>Amount</th><th>Invoice</th><th>Shipment</th><th>Overall</th><th>Priority</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td>{o.marketplace}</td><td>{o.product} × {o.qty}</td><td>₹{o.amount.toLocaleString('en-IN')}</td><td><Badge tone={statusTone(o.invoice)}>{o.invoice}</Badge></td><td><Badge tone={statusTone(o.shipment)}>{o.shipment}</Badge></td><td><Badge tone={statusTone(o.overall)}>{o.overall}</Badge></td><td><Badge tone={priorityTone(o.priority)}>{o.priority}</Badge></td></tr>)}</tbody></table></div></div></>}

function OperationsPage({orders,issues,setIssues}:{orders:Order[];issues:Issue[];setIssues:React.Dispatch<React.SetStateAction<Issue[]>>}){const pending=orders.filter(x=>x.overall==='New'||x.overall==='Processing'),waiting=orders.filter(x=>x.overall==='Waiting'),shipment=orders.filter(x=>x.shipment==='Waiting'||x.shipment==='Failed'),invoice=orders.filter(x=>x.invoice==='Pending');return <><PageTitle eyebrow="Execution" title="Operations" desc="A control center for orders, issues and handoffs."/><div className="ops-grid"><Stat label="Pending" value={pending.length} icon={Clock3} tone="orange"/><Stat label="Waiting" value={waiting.length} icon={Truck} tone="yellow"/><Stat label="Shipment issues" value={shipment.length} icon={AlertCircle} tone="red"/><Stat label="Invoice issues" value={invoice.length} icon={FileText} tone="purple"/></div><div className="card section"><SectionHead title="Issues" icon={AlertCircle} action={<button className="btn" onClick={()=>setIssues(xs=>[{id:uid(),title:'New operational issue',order:'',category:'Internal',owner:'',priority:'Medium',status:'Open',due:today(),resolution:'',notes:''},...xs])}><Plus size={15}/> Add issue</button>}/><div className="issue-list">{issues.map(i=><div className="issue-row" key={i.id}><div className="issue-icon"><AlertCircle size={17}/></div><div className="issue-main"><b>{i.title}</b><small>{i.category} · {i.order||'No order'} · Due {i.due}</small></div><Badge tone={priorityTone(i.priority)}>{i.priority}</Badge><Badge tone={statusTone(i.status)}>{i.status}</Badge><button className="btn small-btn" onClick={()=>setIssues(xs=>xs.map(x=>x.id===i.id?{...x,status:x.status==='Open'?'Resolved':'Open',resolution:x.status==='Open'?'Resolved by user':'',}:x))}>{i.status==='Open'?'Resolve':'Reopen'}</button></div>)}</div></div></>}

function CampaignPage({campaigns,setCampaigns}:{campaigns:Campaign[];setCampaigns:React.Dispatch<React.SetStateAction<Campaign[]>>}){return <><PageTitle eyebrow="Customer retention" title="CRM / OmniFlow planner" desc="Plan campaigns without pretending there is a live OmniFlow connection." action={<button className="btn btn-primary" onClick={()=>setCampaigns(xs=>[{id:uid(),name:'New campaign',type:'Reorder',audience:'',start:today(),end:today(),status:'Idea',targeted:0,sent:0,delivered:0,clicks:0,orders:0,revenue:0,notes:'',results:'',learnings:''},...xs])}><Plus size={16}/> New campaign</button>}/><div className="card section"><div className="campaign-grid">{campaigns.map(c=><div className="campaign-card" key={c.id}><div className="campaign-top"><Badge tone={statusTone(c.status)}>{c.status}</Badge><span>{c.type}</span></div><h3>{c.name}</h3><p>{c.audience||'Audience not defined yet.'}</p><div className="metrics-mini"><div><b>{c.targeted.toLocaleString()}</b><small>Targeted</small></div><div><b>{c.sent.toLocaleString()}</b><small>Sent</small></div><div><b>{c.orders}</b><small>Orders</small></div><div><b>₹{c.revenue.toLocaleString('en-IN')}</b><small>Revenue</small></div></div><div className="campaign-footer">{c.start} → {c.end}<select className="select tiny" value={c.status} onChange={e=>setCampaigns(xs=>xs.map(x=>x.id===c.id?{...x,status:e.target.value}:x))}>{['Idea','Planned','Scheduled','Running','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></div></div>)}</div></div></>}

function GrowthPage({experiments,setExperiments}:{experiments:Experiment[];setExperiments:React.Dispatch<React.SetStateAction<Experiment[]>>}){return <><PageTitle eyebrow="Growth Lab" title="Experiments" desc="Record hypotheses, baselines, targets and learnings. Outcomes stay data-led." action={<button className="btn btn-primary" onClick={()=>setExperiments(xs=>[{id:uid(),name:'New experiment',hypothesis:'',problem:'',action:'',channel:'Website',start:today(),end:today(),metric:'Orders',baseline:'',target:'',result:'',learning:'',decision:'Continue'},...xs])}><Plus size={16}/> New experiment</button>}/><div className="experiment-grid">{experiments.map(e=><div className="card experiment-card" key={e.id}><div className="experiment-head"><Sparkles size={18}/><Badge tone="purple">{e.channel}</Badge></div><h3>{e.name}</h3><div className="experiment-section"><small>HYPOTHESIS</small><p>{e.hypothesis||'Add a testable hypothesis.'}</p></div><div className="experiment-section"><small>PROPOSED ACTION</small><p>{e.action||'Define what will change.'}</p></div><div className="experiment-metrics"><div><small>Metric</small><b>{e.metric}</b></div><div><small>Baseline</small><b>{e.baseline||'—'}</b></div><div><small>Target</small><b>{e.target||'—'}</b></div><div><small>Result</small><b>{e.result||'Not recorded'}</b></div></div><label className="decision">Decision<select className="select" value={e.decision} onChange={ev=>setExperiments(xs=>xs.map(x=>x.id===e.id?{...x,decision:ev.target.value}:x))}>{['Continue','Modify','Stop'].map(s=><option key={s}>{s}</option>)}</select></label><textarea className="textarea" rows={2} placeholder="Learning / result" value={e.learning} onChange={ev=>setExperiments(xs=>xs.map(x=>x.id===e.id?{...x,learning:ev.target.value}:x))}/></div>)}</div></>}

function WebsitePage({tasks,setTasks,projects}:{tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;projects:Project[]}){const items=tasks.filter(t=>t.tags.some(x=>['Website','SEO','Content','Pricing'].includes(x)));return <><PageTitle eyebrow="Website control center" title="Website" desc="Manage website work without directly modifying the live company website." action={<button className="btn btn-primary" onClick={()=>setTasks(xs=>[{id:uid(),title:'New website task',description:'',projectId:projects.find(p=>p.category==='Growth')?.id||projects[0]?.id||'',status:'To Do',priority:'Medium',due:today(),tags:['Website'],subtasks:[],created:today(),updated:today()},...xs])}><Plus size={16}/> Add website task</button>}/><div className="category-strip">{['Website issues','Product updates','Pricing changes','Landing pages','SEO tasks','Conversion improvements','Content','Promotions','Technical issues'].map(x=><div className="category-card" key={x}><Globe2 size={16}/><span>{x}</span></div>)}</div><div className="card section"><SectionHead title="Website work" icon={Globe2}/>{items.length?items.map(t=><TaskRow key={t.id} task={t} onDone={()=>setTasks(xs=>xs.map(x=>x.id===t.id?{...x,status:'Done'}:x))}/>):<Empty text="No website tasks yet."/>}</div></>}

function NotesPage({notes,setNotes,query}:{notes:Note[];setNotes:React.Dispatch<React.SetStateAction<Note[]>>;query:string}){const [editing,setEditing]=useState<Note|null>(null);const filtered=notes.filter(n=>!query||`${n.title} ${n.body} ${n.tag}`.toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="Knowledge base" title="Notes" desc="Founder instructions, meeting notes, SOPs and ideas in one place." action={<button className="btn btn-primary" onClick={()=>setEditing({id:uid(),title:'',body:'',tag:'General',pinned:false,updated:today()})}><Plus size={16}/> New note</button>}/><div className="notes-grid">{filtered.map(n=><div className={'card note-card '+(n.pinned?'pinned':'')} key={n.id}><div className="note-top"><Badge tone="purple">{n.tag}</Badge><button className="icon-btn small" onClick={()=>setNotes(xs=>xs.map(x=>x.id===n.id?{...x,pinned:!x.pinned}:x))}><Tag size={15}/></button></div><h3>{n.title}</h3><p>{n.body}</p><div className="note-footer"><small>{n.updated}</small><button className="link" onClick={()=>setEditing(n)}>Edit</button><button className="link danger" onClick={()=>setNotes(xs=>xs.filter(x=>x.id!==n.id))}>Delete</button></div></div>)}</div>{editing&&<NoteModal note={editing} onClose={()=>setEditing(null)} onSave={n=>{setNotes(xs=>xs.some(x=>x.id===n.id)?xs.map(x=>x.id===n.id?n:x):[n,...xs]);setEditing(null)}}/>}</>}
function NoteModal({note,onClose,onSave}:{note:Note;onClose:()=>void;onSave:(n:Note)=>void}){const [n,setN]=useState(note);return <Modal title={note.title?'Edit note':'New note'} onClose={onClose}><label>Title<input className="input" value={n.title} onChange={e=>setN({...n,title:e.target.value})}/></label><label>Tag<input className="input" value={n.tag} onChange={e=>setN({...n,tag:e.target.value})}/></label><label>Note<textarea className="textarea" rows={8} value={n.body} onChange={e=>setN({...n,body:e.target.value})}/></label><div className="modal-actions"><span/><button className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={()=>onSave({...n,updated:today()})}>Save note</button></div></Modal>}

function Reports({tasks,projects,orders,issues,campaigns,experiments}:{tasks:Task[];projects:Project[];orders:Order[];issues:Issue[];campaigns:Campaign[];experiments:Experiment[]}){const completed=tasks.filter(t=>t.status==='Done').length;const blocked=tasks.filter(t=>t.status==='Blocked').length;const revenue=orders.reduce((a,x)=>a+x.amount,0);return <><PageTitle eyebrow="Founder reporting" title="Reports" desc="A concise operating view for daily and weekly reporting." action={<button className="btn" onClick={()=>window.print()}><FileText size={16}/> Print report</button>}/><div className="report-grid"><div className="card report-card"><div className="eyebrow">DAILY REPORT</div><h3>Today</h3><div className="report-row"><span>Tasks completed</span><b>{completed}</b></div><div className="report-row"><span>Tasks pending</span><b>{tasks.filter(t=>!['Done','Cancelled'].includes(t.status)).length}</b></div><div className="report-row"><span>Blocked tasks</span><b>{blocked}</b></div><div className="report-row"><span>Important issues</span><b>{issues.filter(i=>i.status==='Open').length}</b></div></div><div className="card report-card"><div className="eyebrow">WEEKLY SNAPSHOT</div><h3>Operating pulse</h3><div className="report-row"><span>Active projects</span><b>{projects.filter(p=>p.status==='Active').length}</b></div><div className="report-row"><span>RO / order value</span><b>₹{revenue.toLocaleString('en-IN')}</b></div><div className="report-row"><span>CRM campaigns</span><b>{campaigns.length}</b></div><div className="report-row"><span>Growth experiments</span><b>{experiments.length}</b></div></div></div><div className="card section"><SectionHead title="Founder report outline" icon={FileText}/><div className="report-outline"><div><b>1. Completed work</b><p>Summarize completed tasks and projects.</p></div><div><b>2. E-commerce numbers</b><p>Orders, revenue, AOV and marketplace movement.</p></div><div><b>3. Operations</b><p>Waiting orders, shipment issues and invoice issues.</p></div><div><b>4. CRM & Growth</b><p>Campaigns, experiments, results and learnings.</p></div><div><b>5. Next week</b><p>List the next priorities and open dependencies.</p></div></div></div></>}

function SettingsPage(){return <><PageTitle eyebrow="Workspace" title="Settings" desc="Local demo settings and future integration controls."/><div className="settings-grid"><div className="card setting-card"><div className="setting-icon"><Settings size={18}/></div><h3>Workspace</h3><p>Impact Water · E-commerce & Growth OS</p><span className="setting-status">Demo mode active</span></div><div className="card setting-card"><div className="setting-icon"><Zap size={18}/></div><h3>Integrations</h3><p>Blinkit, Zepto, OmniFlow, WhatsApp and website integrations are intentionally not connected.</p><span className="setting-status">Ready for API configuration</span></div><div className="card setting-card"><div className="setting-icon"><BriefcaseBusiness size={18}/></div><h3>Security</h3><p>Secrets belong in environment variables. Production authorization should be enforced through Supabase RLS.</p><span className="setting-status">Configuration required for production</span></div></div></>}

function QuickAdd({onClose,setPage,setTasks,setProjects,setOrders,setNotes,setIssues,setCampaigns,setExperiments}:{onClose:()=>void;setPage:(x:string)=>void;setTasks:any;setProjects:any;setOrders:any;setNotes:any;setIssues:any;setCampaigns:any;setExperiments:any}){const add=(type:string)=>{if(type==='Task'){setTasks((xs:Task[])=>[{id:uid(),title:'New task',description:'',projectId:'p1',status:'To Do',priority:'Medium',due:today(),tags:[],subtasks:[],created:today(),updated:today()},...xs]);setPage('Tasks')}if(type==='Project'){setProjects((xs:Project[])=>[{id:uid(),name:'New project',description:'',status:'Planning',priority:'Medium',category:'E-Commerce',due:today(),goals:''},...xs]);setPage('Projects')}if(type==='Order / RO'){setOrders((xs:Order[])=>[{id:'RO-'+Math.floor(Math.random()*9000+1000),marketplace:'Other',date:today(),product:'',qty:0,amount:0,invoice:'Pending',shipment:'Not Started',overall:'New',priority:'Medium',owner:'',notes:''},...xs]);setPage('E-Commerce')}if(type==='CRM Campaign'){setCampaigns((xs:Campaign[])=>[{id:uid(),name:'New campaign',type:'Reorder',audience:'',start:today(),end:today(),status:'Idea',targeted:0,sent:0,delivered:0,clicks:0,orders:0,revenue:0,notes:'',results:'',learnings:''},...xs]);setPage('CRM')}if(type==='Growth Experiment'){setExperiments((xs:Experiment[])=>[{id:uid(),name:'New experiment',hypothesis:'',problem:'',action:'',channel:'Website',start:today(),end:today(),metric:'Orders',baseline:'',target:'',result:'',learning:'',decision:'Continue'},...xs]);setPage('Growth')}if(type==='Note'){setNotes((xs:Note[])=>[{id:uid(),title:'New note',body:'',tag:'General',pinned:false,updated:today()},...xs]);setPage('Notes')}if(type==='Issue'){setIssues((xs:Issue[])=>[{id:uid(),title:'New operational issue',order:'',category:'Internal',owner:'',priority:'Medium',status:'Open',due:today(),resolution:'',notes:''},...xs]);setPage('Operations')}onClose()};return <div className="modal-backdrop" onMouseDown={onClose}><div className="quick-menu" onMouseDown={e=>e.stopPropagation()}><div className="quick-head"><div><b>Quick add</b><small>Create something without leaving your workflow.</small></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{['Task','Project','Order / RO','CRM Campaign','Growth Experiment','Note','Issue'].map(x=><button className="quick-option" key={x} onClick={()=>add(x)}><Plus size={17}/><span>{x}</span><ChevronDown size={15}/></button>)}</div></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><b>{title}</b><small>Changes are saved to this workspace.</small></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
